name: 'Docker Build'
description: 'Build and push Docker image to GitHub Container Registry'

inputs:
  version:
    description: 'Version tag for the image'
    required: true
  image_name:
    description: 'Docker image name (without registry prefix)'
    required: true
  push:
    description: 'Push to registry'
    required: false
    default: 'true'
  github_token:
    description: 'GitHub token for registry authentication'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.github_token }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: ${{ inputs.push }}
        tags: |
          ghcr.io/${{ github.repository_owner }}/${{ inputs.image_name }}:latest
          ghcr.io/${{ github.repository_owner }}/${{ inputs.image_name }}:v${{ inputs.version }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
